name: UltraList
version: '${version}'
api-version: '1.18'
authors: [ "404" ]
description: "Ultralist brings enhanced player lists and plugin lists"
website: https://tranic.one
main: one.tranic.ultralist.bukkit.Main
load: STARTUP
folia-supported: true
commands:
  plugins:
    description: "plugins command"
    permission: ultralist.plugins
  list:
    description: "list command"
    permission: ultralist.list
permissions:
  ultralist.plugins:
    default: op
  ultralist.list:
    default: op
depend:
  - MavenLoader
libraries:
  - net.kyori:adventure-platform-bukkit:4.3.4
  - net.kyori:adventure-text-minimessage:4.17.0