name: UltraList
version: '${version}'
api-version: '1.18'
authors: [ "404" ]
description: "Ultralist brings enhanced player lists and plugin lists"
website: https://tranic.one
main: one.tranic.ultralist.paper.Main
load: STARTUP
folia-supported: true
permissions:
  ultralist.plugins:
    default: op
  ultralist.list:
    default: op
depend:
  - MavenLoader
libraries:
  - it.unimi.dsi:fastutil:8.5.13